### ISSUE TITLE
Discounting a percentage on order

### ISSUE THREAD

**Issue by stickypages** [wp-premium/woocommerce-table-rate-shipping#2]
There seems to be a feature missing in your plugin, which I thought it would cover. 
When adding a 'discount' to a shipping method, this does not work. 

If they select Option 1: Discount 15% on row. 
This is totally ignored. It would be massive if we could adjust this.

**Comment by remcotolsma** [comment]
> WooCommerce Table Rate Shipping, Git-ified. Synced manual! This repository is just a mirror of the WooCommerce Table Rate Shipping plugin. Please do not send pull requests and issues.

https://github.com/wp-premium/woocommerce-table-rate-shipping
