### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by piyush138** [wp-premium/woocommerce-table-rate-shipping#3]
Error is:  Call to a member function needs_shipping() on null in /wp-content/plugins/woocommerce-table-rate-shipping/includes/class-wc-shipping-table-rate.php on line 318

Data coming in $package is 

Array ( [contents] => Array ( [38af86134b65d0f10fe33d30dd76442e] => 10 [b071cfa81605a94ad80cfa2bbc747448] => 7.5 ) [contents_cost] => 17.5 [applied_coupons] => Array ( ) [user] => Array ( [ID] => 1003674 ) [destination] => Array ( [country] => US [state] => AR [postcode] => [city] => [address] => [address_2] => ) [cart_subtotal] => 17.5 [rates] => Array ( ) ) 

I am using multisite installation.

**Comment by remcotolsma** [comment]
Please contact WooCommerce support for issues.

> This repository is just a mirror of the WooCommerce Table Rate Shipping plugin. Please do not send pull requests and issues.

https://github.com/wp-premium/woocommerce-table-rate-shipping
